import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      {/* <Dummy /> */}
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <span className={styles.h1}><h1>&lt;Hunting Coders/&gt;</h1></span>
        <div className={styles.imagewrapper}>
          {/* <Image className={styles.myImg} src="/home.jpg" width={350} height={350} /> */}
          <img className={styles.myImg} src="/home.jpg" width={150} height={150} alt="hunting coder" />
        </div>
        <div className={styles.blogs}>
          <h2 className={styles.h2}>Popular Blogs</h2>
          <div>
            <h3 className={styles.blogItem}>How to learn javascript in 2023?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, dolores.</p>
            {/* <Link href={'blog'}><button className={styles.btn}>Read More</button></Link> */}
            <Link href='blog'>
            <button className={styles.btn}>Read More</button></Link>
          </div>
          <div>
            <h3 className={styles.blogItem}>How to learn Next.js in 2023?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, dolores.</p>
            <Link href='blog'>
            <button className={styles.btn}>Read More</button></Link> 
          </div>
          <div>
            <h3 className={styles.blogItem}>How to learn Node.js in 2023?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, dolores.</p>
            <Link href='blog'>
            <button className={styles.btn}>Read More</button></Link>
          </div>
        </div>
      </main>
    </>
  )
}
